---
name: show secrets

on:
  workflow_dispatch:

jobs:
  echo_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Show secret with spaces in between
        run: echo ${{secrets.MY_SECRET }} | sed 's/./& /g'
